/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export * as factories from './factories'
export { RedPacket__factory } from './factories/RedPacket__factory'
export type { RedPacket } from './RedPacket'
